name: Create Nested workflow

on: 
  push:
    branches:
      - '!main'
      - 'feat/*'
jobs:
  on-push:
    uses: ./.github/workflows/create-environment.yml
    with:
      gh-env-name: 'test-environment'