name: Delete Nested workflow

on: delete

jobs:
  on-delete:
    uses: psilore/on-delete-event/.github/workflows/delete-environment.yml@9048cba85504591a4e8c4d7c2c2389280960447d
    with:
      gh-env-name: ${{ github.ref }}
    secrets:
      token: ${{ secrets.GH_PAT }} # scopes: repo, Full control of private repositories
