name: Delete Nested workflow

on: push

jobs:
  on-delete:
    uses: ./.github/workflows/delete-environment.yml
    with:
      gh-env-name: ${{ github.ref }}
    secrets:
      token: ${{ secrets.GH_PAT }} # scopes: repo, Full control of private repositories